/** Effect ids that have form fields — unknown ones must still pick from the list. */
export const VISUAL_EFFECT_IDS = [
  "production_mult",
  "upkeep_mult",
  "flow_convert",
  "capacity_add",
  "rate_mod",
  "demand_mod",
  "pop_cap_add",
  "pop_cap_flat",
  "loyalty_add",
  "stability_add",
  "ap_add",
  "pop_growth_mult",
  "habitability_mult",
  "diplomacy_trust_decay_mult",
  "research_cost_mult",
  "combat_role_mult",
  "unlock_tech_tier",
  "unlock_property",
  "open_path",
  "production_flat",
  "yield_flat",
  "upkeep_flat",
  "stat_mult",
  "cost_mult",
] as const;
