import { applyMoveFleet, applyMoveLegion, applyBlockade, applyFortify } from "./movement.mjs";
import {
  applyClaim,
  applyAttackMarker,
  applyCombatStance,
  applyRequestCardBattle,
  applyPlayCard,
} from "./combatIntents.mjs";
import {
  applyScoutReveal,
  applyScoutWorld,
  applyEspionage,
} from "./intelIntents.mjs";
import {
  applySetTax,
  applySetFlowPriority,
  applyReserveStock,
  applySendCaravan,
  applySetEconomicPolicy,
  applyTransfer,
  applyBreakTreaty,
  applyMarketConvert,
  applyMarketOffer,
  applyMarketCancel,
  applyMakeDiploOffer,
} from "./economyIntents.mjs";
import {
  applyPlanetIntent,
  applyResearchUpgrade,
  applySetResearchQueue,
  applySetBuildQueue,
  applyFoundHybridLineage,
  applyTradeTech,
  applyGrantPowerTouch,
} from "./researchBuild.mjs";
import {
  applyRefugeeConvoyIntent,
  applyGiveNpcTask,
  applyAssignNpcPosting,
  applyRecallNpcPosting,
  applySeatNpcCouncil,
  applyUnseatNpcCouncil,
  applySetCouncilPortfolio,
  applyAssignBlocLeader,
  applyAssignRaceLeader,
} from "./npcIntents.mjs";
import {
  applyThrowQuestDice,
  applyResolveQuestChoice,
  applyResolveQuestDice,
} from "../questActions.mjs";

export const APPLIERS = {
  "intent.move_fleet": applyMoveFleet,
  "intent.move_legion": applyMoveLegion,
  "intent.claim_system": applyClaim,
  "intent.attack_system": applyAttackMarker,
  "intent.blockade": applyBlockade,
  "intent.fortify": applyFortify,
  "intent.combat_stance": applyCombatStance,
  "intent.request_card_battle": applyRequestCardBattle,
  "intent.play_card": applyPlayCard,
  "intent.scout_reveal": applyScoutReveal,
  "intent.scout_world": applyScoutWorld,
  "intent.espionage": applyEspionage,
  "intent.set_tax": applySetTax,
  "intent.set_flow_priority": applySetFlowPriority,
  "intent.reserve_stock": applyReserveStock,
  "intent.send_caravan": applySendCaravan,
  "intent.set_economic_policy": applySetEconomicPolicy,
  "intent.transfer": applyTransfer,
  "intent.break_treaty": applyBreakTreaty,
  "intent.market_convert": applyMarketConvert,
  "intent.market_offer": applyMarketOffer,
  "intent.market_cancel": applyMarketCancel,
  "intent.refugee_convoy": applyRefugeeConvoyIntent,
  "intent.give_npc_task": applyGiveNpcTask,
  "intent.assign_npc_posting": applyAssignNpcPosting,
  "intent.recall_npc_posting": applyRecallNpcPosting,
  "intent.seat_npc_council": applySeatNpcCouncil,
  "intent.unseat_npc_council": applyUnseatNpcCouncil,
  "intent.set_council_portfolio": applySetCouncilPortfolio,
  "intent.assign_bloc_leader": applyAssignBlocLeader,
  "intent.assign_race_leader": applyAssignRaceLeader,
  "intent.research_upgrade": applyResearchUpgrade,
  "intent.set_research_queue": applySetResearchQueue,
  "intent.set_build_queue": applySetBuildQueue,
  "intent.found_hybrid_lineage": applyFoundHybridLineage,
  "intent.trade_tech": applyTradeTech,
  "intent.throw_quest_dice": applyThrowQuestDice,
  "intent.resolve_quest_choice": applyResolveQuestChoice,
  "intent.resolve_quest_dice": applyResolveQuestDice,
  "intent.gm.grant_power_touch": applyGrantPowerTouch,
  "intent.build": applyPlanetIntent("build"),
  "intent.demolish": applyPlanetIntent("demolish"),
  "intent.colonize": applyPlanetIntent("colonize"),
  "intent.set_colony_type": applyPlanetIntent("set_colony_type"),
  "intent.upgrade_grade": applyPlanetIntent("upgrade_grade"),
  "intent.make_diplo_offer": applyMakeDiploOffer,
};
